/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.tAB;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Colonne Input</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.tAB.TABPackage#getColonneInput()
 * @model
 * @generated
 */
public interface ColonneInput extends Colonne
{
} // ColonneInput
