/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.tAB;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entree Script</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.tAB.EntreeScript#getParametres <em>Parametres</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.tAB.TABPackage#getEntreeScript()
 * @model
 * @generated
 */
public interface EntreeScript extends EObject
{
  /**
   * Returns the value of the '<em><b>Parametres</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.tAB.Parametre}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parametres</em>' containment reference list.
   * @see org.xtext.example.mydsl.tAB.TABPackage#getEntreeScript_Parametres()
   * @model containment="true"
   * @generated
   */
  EList<Parametre> getParametres();

} // EntreeScript
