/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.tAB;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation Binaire Script</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.tAB.OperationBinaireScript#getOperation <em>Operation</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.tAB.OperationBinaireScript#getOperand <em>Operand</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.tAB.TABPackage#getOperationBinaireScript()
 * @model
 * @generated
 */
public interface OperationBinaireScript extends OperationScript
{
  /**
   * Returns the value of the '<em><b>Operation</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.tAB.OperateurBinaireType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operation</em>' attribute.
   * @see org.xtext.example.mydsl.tAB.OperateurBinaireType
   * @see #setOperation(OperateurBinaireType)
   * @see org.xtext.example.mydsl.tAB.TABPackage#getOperationBinaireScript_Operation()
   * @model
   * @generated
   */
  OperateurBinaireType getOperation();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.tAB.OperationBinaireScript#getOperation <em>Operation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operation</em>' attribute.
   * @see org.xtext.example.mydsl.tAB.OperateurBinaireType
   * @see #getOperation()
   * @generated
   */
  void setOperation(OperateurBinaireType value);

  /**
   * Returns the value of the '<em><b>Operand</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.tAB.Operand}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operand</em>' containment reference list.
   * @see org.xtext.example.mydsl.tAB.TABPackage#getOperationBinaireScript_Operand()
   * @model containment="true"
   * @generated
   */
  EList<Operand> getOperand();

} // OperationBinaireScript
