/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.tAB;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.tAB.TABFactory
 * @model kind="package"
 * @generated
 */
public interface TABPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "tAB";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/TAB";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "tAB";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TABPackage eINSTANCE = org.xtext.example.mydsl.tAB.impl.TABPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.tAB.impl.TableurImpl <em>Tableur</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.tAB.impl.TableurImpl
   * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getTableur()
   * @generated
   */
  int TABLEUR = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLEUR__NAME = 0;

  /**
   * The feature id for the '<em><b>Tables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLEUR__TABLES = 1;

  /**
   * The feature id for the '<em><b>Catalogue</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLEUR__CATALOGUE = 2;

  /**
   * The feature id for the '<em><b>Script</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLEUR__SCRIPT = 3;

  /**
   * The number of structural features of the '<em>Tableur</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLEUR_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.tAB.impl.ColonneImpl <em>Colonne</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.tAB.impl.ColonneImpl
   * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getColonne()
   * @generated
   */
  int COLONNE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE__NAME = 0;

  /**
   * The number of structural features of the '<em>Colonne</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.tAB.impl.OperationImpl <em>Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.tAB.impl.OperationImpl
   * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getOperation()
   * @generated
   */
  int OPERATION = 2;

  /**
   * The number of structural features of the '<em>Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.tAB.impl.OperateurUnaireImpl <em>Operateur Unaire</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.tAB.impl.OperateurUnaireImpl
   * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getOperateurUnaire()
   * @generated
   */
  int OPERATEUR_UNAIRE = 3;

  /**
   * The feature id for the '<em><b>Kind</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATEUR_UNAIRE__KIND = OPERATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Operateur Unaire</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATEUR_UNAIRE_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.tAB.impl.OperateurBinaireImpl <em>Operateur Binaire</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.tAB.impl.OperateurBinaireImpl
   * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getOperateurBinaire()
   * @generated
   */
  int OPERATEUR_BINAIRE = 4;

  /**
   * The feature id for the '<em><b>Kind</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATEUR_BINAIRE__KIND = OPERATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Operateur Binaire</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATEUR_BINAIRE_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.tAB.impl.TableImpl <em>Table</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.tAB.impl.TableImpl
   * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getTable()
   * @generated
   */
  int TABLE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE__NAME = 0;

  /**
   * The feature id for the '<em><b>Colonnes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE__COLONNES = 1;

  /**
   * The number of structural features of the '<em>Table</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.tAB.impl.ColonneInputImpl <em>Colonne Input</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.tAB.impl.ColonneInputImpl
   * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getColonneInput()
   * @generated
   */
  int COLONNE_INPUT = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE_INPUT__NAME = COLONNE__NAME;

  /**
   * The number of structural features of the '<em>Colonne Input</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE_INPUT_FEATURE_COUNT = COLONNE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.tAB.impl.ColonneOutputImpl <em>Colonne Output</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.tAB.impl.ColonneOutputImpl
   * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getColonneOutput()
   * @generated
   */
  int COLONNE_OUTPUT = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE_OUTPUT__NAME = COLONNE__NAME;

  /**
   * The feature id for the '<em><b>Operations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE_OUTPUT__OPERATIONS = COLONNE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Colonnes</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE_OUTPUT__COLONNES = COLONNE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Colonne Output</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE_OUTPUT_FEATURE_COUNT = COLONNE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.tAB.impl.CatalogueImpl <em>Catalogue</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.tAB.impl.CatalogueImpl
   * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getCatalogue()
   * @generated
   */
  int CATALOGUE = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CATALOGUE__NAME = 0;

  /**
   * The feature id for the '<em><b>Algorithmes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CATALOGUE__ALGORITHMES = 1;

  /**
   * The number of structural features of the '<em>Catalogue</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CATALOGUE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.tAB.impl.AlgorithmeImpl <em>Algorithme</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.tAB.impl.AlgorithmeImpl
   * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getAlgorithme()
   * @generated
   */
  int ALGORITHME = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHME__NAME = 0;

  /**
   * The feature id for the '<em><b>Entrees</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHME__ENTREES = 1;

  /**
   * The feature id for the '<em><b>Sorties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHME__SORTIES = 2;

  /**
   * The feature id for the '<em><b>Documentation</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHME__DOCUMENTATION = 3;

  /**
   * The feature id for the '<em><b>Ressource</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHME__RESSOURCE = 4;

  /**
   * The number of structural features of the '<em>Algorithme</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHME_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.tAB.impl.EntreeImpl <em>Entree</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.tAB.impl.EntreeImpl
   * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getEntree()
   * @generated
   */
  int ENTREE = 10;

  /**
   * The feature id for the '<em><b>Parametres</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTREE__PARAMETRES = 0;

  /**
   * The number of structural features of the '<em>Entree</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTREE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.tAB.impl.SortieImpl <em>Sortie</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.tAB.impl.SortieImpl
   * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getSortie()
   * @generated
   */
  int SORTIE = 11;

  /**
   * The feature id for the '<em><b>Parametres</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SORTIE__PARAMETRES = 0;

  /**
   * The number of structural features of the '<em>Sortie</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SORTIE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.tAB.impl.ParametreImpl <em>Parametre</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.tAB.impl.ParametreImpl
   * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getParametre()
   * @generated
   */
  int PARAMETRE = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETRE__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETRE__TYPE = 1;

  /**
   * The number of structural features of the '<em>Parametre</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETRE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.tAB.impl.DocumentationImpl <em>Documentation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.tAB.impl.DocumentationImpl
   * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getDocumentation()
   * @generated
   */
  int DOCUMENTATION = 13;

  /**
   * The feature id for the '<em><b>Texte</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOCUMENTATION__TEXTE = 0;

  /**
   * The number of structural features of the '<em>Documentation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOCUMENTATION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.tAB.impl.RessourceImpl <em>Ressource</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.tAB.impl.RessourceImpl
   * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getRessource()
   * @generated
   */
  int RESSOURCE = 14;

  /**
   * The feature id for the '<em><b>Chemin</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESSOURCE__CHEMIN = 0;

  /**
   * The number of structural features of the '<em>Ressource</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESSOURCE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.tAB.impl.ScriptImpl <em>Script</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.tAB.impl.ScriptImpl
   * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getScript()
   * @generated
   */
  int SCRIPT = 15;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCRIPT__NAME = 0;

  /**
   * The feature id for the '<em><b>Entrees</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCRIPT__ENTREES = 1;

  /**
   * The feature id for the '<em><b>Sorties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCRIPT__SORTIES = 2;

  /**
   * The feature id for the '<em><b>Calculs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCRIPT__CALCULS = 3;

  /**
   * The number of structural features of the '<em>Script</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCRIPT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.tAB.impl.EntreeScriptImpl <em>Entree Script</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.tAB.impl.EntreeScriptImpl
   * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getEntreeScript()
   * @generated
   */
  int ENTREE_SCRIPT = 16;

  /**
   * The feature id for the '<em><b>Parametres</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTREE_SCRIPT__PARAMETRES = 0;

  /**
   * The number of structural features of the '<em>Entree Script</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTREE_SCRIPT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.tAB.impl.SortieScriptImpl <em>Sortie Script</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.tAB.impl.SortieScriptImpl
   * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getSortieScript()
   * @generated
   */
  int SORTIE_SCRIPT = 17;

  /**
   * The feature id for the '<em><b>Parametres</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SORTIE_SCRIPT__PARAMETRES = 0;

  /**
   * The number of structural features of the '<em>Sortie Script</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SORTIE_SCRIPT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.tAB.impl.OperandImpl <em>Operand</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.tAB.impl.OperandImpl
   * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getOperand()
   * @generated
   */
  int OPERAND = 21;

  /**
   * The number of structural features of the '<em>Operand</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERAND_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.tAB.impl.OperationScriptImpl <em>Operation Script</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.tAB.impl.OperationScriptImpl
   * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getOperationScript()
   * @generated
   */
  int OPERATION_SCRIPT = 18;

  /**
   * The number of structural features of the '<em>Operation Script</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_SCRIPT_FEATURE_COUNT = OPERAND_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.tAB.impl.OperationUnaireScriptImpl <em>Operation Unaire Script</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.tAB.impl.OperationUnaireScriptImpl
   * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getOperationUnaireScript()
   * @generated
   */
  int OPERATION_UNAIRE_SCRIPT = 19;

  /**
   * The feature id for the '<em><b>Operation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_UNAIRE_SCRIPT__OPERATION = OPERATION_SCRIPT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_UNAIRE_SCRIPT__OPERANDS = OPERATION_SCRIPT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Operation Unaire Script</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_UNAIRE_SCRIPT_FEATURE_COUNT = OPERATION_SCRIPT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.tAB.impl.OperationBinaireScriptImpl <em>Operation Binaire Script</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.tAB.impl.OperationBinaireScriptImpl
   * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getOperationBinaireScript()
   * @generated
   */
  int OPERATION_BINAIRE_SCRIPT = 20;

  /**
   * The feature id for the '<em><b>Operation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_BINAIRE_SCRIPT__OPERATION = OPERATION_SCRIPT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operand</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_BINAIRE_SCRIPT__OPERAND = OPERATION_SCRIPT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Operation Binaire Script</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_BINAIRE_SCRIPT_FEATURE_COUNT = OPERATION_SCRIPT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.tAB.impl.CalculImpl <em>Calcul</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.tAB.impl.CalculImpl
   * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getCalcul()
   * @generated
   */
  int CALCUL = 22;

  /**
   * The feature id for the '<em><b>Operation</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALCUL__OPERATION = 0;

  /**
   * The number of structural features of the '<em>Calcul</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALCUL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.tAB.OperationUnaireType <em>Operation Unaire Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.tAB.OperationUnaireType
   * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getOperationUnaireType()
   * @generated
   */
  int OPERATION_UNAIRE_TYPE = 23;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.tAB.OperationBinaireType <em>Operation Binaire Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.tAB.OperationBinaireType
   * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getOperationBinaireType()
   * @generated
   */
  int OPERATION_BINAIRE_TYPE = 24;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.tAB.TypePrimitifPython <em>Type Primitif Python</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.tAB.TypePrimitifPython
   * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getTypePrimitifPython()
   * @generated
   */
  int TYPE_PRIMITIF_PYTHON = 25;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.tAB.OperateurBinaireType <em>Operateur Binaire Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.tAB.OperateurBinaireType
   * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getOperateurBinaireType()
   * @generated
   */
  int OPERATEUR_BINAIRE_TYPE = 26;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.tAB.OperateurUnaireType <em>Operateur Unaire Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.tAB.OperateurUnaireType
   * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getOperateurUnaireType()
   * @generated
   */
  int OPERATEUR_UNAIRE_TYPE = 27;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.tAB.Tableur <em>Tableur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tableur</em>'.
   * @see org.xtext.example.mydsl.tAB.Tableur
   * @generated
   */
  EClass getTableur();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.tAB.Tableur#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.tAB.Tableur#getName()
   * @see #getTableur()
   * @generated
   */
  EAttribute getTableur_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.tAB.Tableur#getTables <em>Tables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tables</em>'.
   * @see org.xtext.example.mydsl.tAB.Tableur#getTables()
   * @see #getTableur()
   * @generated
   */
  EReference getTableur_Tables();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.tAB.Tableur#getCatalogue <em>Catalogue</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Catalogue</em>'.
   * @see org.xtext.example.mydsl.tAB.Tableur#getCatalogue()
   * @see #getTableur()
   * @generated
   */
  EReference getTableur_Catalogue();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.tAB.Tableur#getScript <em>Script</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Script</em>'.
   * @see org.xtext.example.mydsl.tAB.Tableur#getScript()
   * @see #getTableur()
   * @generated
   */
  EReference getTableur_Script();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.tAB.Colonne <em>Colonne</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Colonne</em>'.
   * @see org.xtext.example.mydsl.tAB.Colonne
   * @generated
   */
  EClass getColonne();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.tAB.Colonne#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.tAB.Colonne#getName()
   * @see #getColonne()
   * @generated
   */
  EAttribute getColonne_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.tAB.Operation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operation</em>'.
   * @see org.xtext.example.mydsl.tAB.Operation
   * @generated
   */
  EClass getOperation();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.tAB.OperateurUnaire <em>Operateur Unaire</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operateur Unaire</em>'.
   * @see org.xtext.example.mydsl.tAB.OperateurUnaire
   * @generated
   */
  EClass getOperateurUnaire();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.tAB.OperateurUnaire#getKind <em>Kind</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Kind</em>'.
   * @see org.xtext.example.mydsl.tAB.OperateurUnaire#getKind()
   * @see #getOperateurUnaire()
   * @generated
   */
  EAttribute getOperateurUnaire_Kind();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.tAB.OperateurBinaire <em>Operateur Binaire</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operateur Binaire</em>'.
   * @see org.xtext.example.mydsl.tAB.OperateurBinaire
   * @generated
   */
  EClass getOperateurBinaire();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.tAB.OperateurBinaire#getKind <em>Kind</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Kind</em>'.
   * @see org.xtext.example.mydsl.tAB.OperateurBinaire#getKind()
   * @see #getOperateurBinaire()
   * @generated
   */
  EAttribute getOperateurBinaire_Kind();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.tAB.Table <em>Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Table</em>'.
   * @see org.xtext.example.mydsl.tAB.Table
   * @generated
   */
  EClass getTable();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.tAB.Table#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.tAB.Table#getName()
   * @see #getTable()
   * @generated
   */
  EAttribute getTable_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.tAB.Table#getColonnes <em>Colonnes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Colonnes</em>'.
   * @see org.xtext.example.mydsl.tAB.Table#getColonnes()
   * @see #getTable()
   * @generated
   */
  EReference getTable_Colonnes();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.tAB.ColonneInput <em>Colonne Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Colonne Input</em>'.
   * @see org.xtext.example.mydsl.tAB.ColonneInput
   * @generated
   */
  EClass getColonneInput();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.tAB.ColonneOutput <em>Colonne Output</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Colonne Output</em>'.
   * @see org.xtext.example.mydsl.tAB.ColonneOutput
   * @generated
   */
  EClass getColonneOutput();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.tAB.ColonneOutput#getOperations <em>Operations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Operations</em>'.
   * @see org.xtext.example.mydsl.tAB.ColonneOutput#getOperations()
   * @see #getColonneOutput()
   * @generated
   */
  EReference getColonneOutput_Operations();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.tAB.ColonneOutput#getColonnes <em>Colonnes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Colonnes</em>'.
   * @see org.xtext.example.mydsl.tAB.ColonneOutput#getColonnes()
   * @see #getColonneOutput()
   * @generated
   */
  EReference getColonneOutput_Colonnes();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.tAB.Catalogue <em>Catalogue</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Catalogue</em>'.
   * @see org.xtext.example.mydsl.tAB.Catalogue
   * @generated
   */
  EClass getCatalogue();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.tAB.Catalogue#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.tAB.Catalogue#getName()
   * @see #getCatalogue()
   * @generated
   */
  EAttribute getCatalogue_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.tAB.Catalogue#getAlgorithmes <em>Algorithmes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Algorithmes</em>'.
   * @see org.xtext.example.mydsl.tAB.Catalogue#getAlgorithmes()
   * @see #getCatalogue()
   * @generated
   */
  EReference getCatalogue_Algorithmes();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.tAB.Algorithme <em>Algorithme</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Algorithme</em>'.
   * @see org.xtext.example.mydsl.tAB.Algorithme
   * @generated
   */
  EClass getAlgorithme();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.tAB.Algorithme#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.tAB.Algorithme#getName()
   * @see #getAlgorithme()
   * @generated
   */
  EAttribute getAlgorithme_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.tAB.Algorithme#getEntrees <em>Entrees</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entrees</em>'.
   * @see org.xtext.example.mydsl.tAB.Algorithme#getEntrees()
   * @see #getAlgorithme()
   * @generated
   */
  EReference getAlgorithme_Entrees();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.tAB.Algorithme#getSorties <em>Sorties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sorties</em>'.
   * @see org.xtext.example.mydsl.tAB.Algorithme#getSorties()
   * @see #getAlgorithme()
   * @generated
   */
  EReference getAlgorithme_Sorties();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.tAB.Algorithme#getDocumentation <em>Documentation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Documentation</em>'.
   * @see org.xtext.example.mydsl.tAB.Algorithme#getDocumentation()
   * @see #getAlgorithme()
   * @generated
   */
  EReference getAlgorithme_Documentation();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.tAB.Algorithme#getRessource <em>Ressource</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Ressource</em>'.
   * @see org.xtext.example.mydsl.tAB.Algorithme#getRessource()
   * @see #getAlgorithme()
   * @generated
   */
  EReference getAlgorithme_Ressource();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.tAB.Entree <em>Entree</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entree</em>'.
   * @see org.xtext.example.mydsl.tAB.Entree
   * @generated
   */
  EClass getEntree();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.tAB.Entree#getParametres <em>Parametres</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parametres</em>'.
   * @see org.xtext.example.mydsl.tAB.Entree#getParametres()
   * @see #getEntree()
   * @generated
   */
  EReference getEntree_Parametres();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.tAB.Sortie <em>Sortie</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sortie</em>'.
   * @see org.xtext.example.mydsl.tAB.Sortie
   * @generated
   */
  EClass getSortie();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.tAB.Sortie#getParametres <em>Parametres</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parametres</em>'.
   * @see org.xtext.example.mydsl.tAB.Sortie#getParametres()
   * @see #getSortie()
   * @generated
   */
  EReference getSortie_Parametres();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.tAB.Parametre <em>Parametre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parametre</em>'.
   * @see org.xtext.example.mydsl.tAB.Parametre
   * @generated
   */
  EClass getParametre();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.tAB.Parametre#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.tAB.Parametre#getName()
   * @see #getParametre()
   * @generated
   */
  EAttribute getParametre_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.tAB.Parametre#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.example.mydsl.tAB.Parametre#getType()
   * @see #getParametre()
   * @generated
   */
  EAttribute getParametre_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.tAB.Documentation <em>Documentation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Documentation</em>'.
   * @see org.xtext.example.mydsl.tAB.Documentation
   * @generated
   */
  EClass getDocumentation();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.tAB.Documentation#getTexte <em>Texte</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Texte</em>'.
   * @see org.xtext.example.mydsl.tAB.Documentation#getTexte()
   * @see #getDocumentation()
   * @generated
   */
  EAttribute getDocumentation_Texte();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.tAB.Ressource <em>Ressource</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ressource</em>'.
   * @see org.xtext.example.mydsl.tAB.Ressource
   * @generated
   */
  EClass getRessource();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.tAB.Ressource#getChemin <em>Chemin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Chemin</em>'.
   * @see org.xtext.example.mydsl.tAB.Ressource#getChemin()
   * @see #getRessource()
   * @generated
   */
  EAttribute getRessource_Chemin();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.tAB.Script <em>Script</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Script</em>'.
   * @see org.xtext.example.mydsl.tAB.Script
   * @generated
   */
  EClass getScript();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.tAB.Script#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.tAB.Script#getName()
   * @see #getScript()
   * @generated
   */
  EAttribute getScript_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.tAB.Script#getEntrees <em>Entrees</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entrees</em>'.
   * @see org.xtext.example.mydsl.tAB.Script#getEntrees()
   * @see #getScript()
   * @generated
   */
  EReference getScript_Entrees();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.tAB.Script#getSorties <em>Sorties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sorties</em>'.
   * @see org.xtext.example.mydsl.tAB.Script#getSorties()
   * @see #getScript()
   * @generated
   */
  EReference getScript_Sorties();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.tAB.Script#getCalculs <em>Calculs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Calculs</em>'.
   * @see org.xtext.example.mydsl.tAB.Script#getCalculs()
   * @see #getScript()
   * @generated
   */
  EReference getScript_Calculs();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.tAB.EntreeScript <em>Entree Script</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entree Script</em>'.
   * @see org.xtext.example.mydsl.tAB.EntreeScript
   * @generated
   */
  EClass getEntreeScript();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.tAB.EntreeScript#getParametres <em>Parametres</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parametres</em>'.
   * @see org.xtext.example.mydsl.tAB.EntreeScript#getParametres()
   * @see #getEntreeScript()
   * @generated
   */
  EReference getEntreeScript_Parametres();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.tAB.SortieScript <em>Sortie Script</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sortie Script</em>'.
   * @see org.xtext.example.mydsl.tAB.SortieScript
   * @generated
   */
  EClass getSortieScript();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.tAB.SortieScript#getParametres <em>Parametres</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parametres</em>'.
   * @see org.xtext.example.mydsl.tAB.SortieScript#getParametres()
   * @see #getSortieScript()
   * @generated
   */
  EReference getSortieScript_Parametres();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.tAB.OperationScript <em>Operation Script</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operation Script</em>'.
   * @see org.xtext.example.mydsl.tAB.OperationScript
   * @generated
   */
  EClass getOperationScript();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.tAB.OperationUnaireScript <em>Operation Unaire Script</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operation Unaire Script</em>'.
   * @see org.xtext.example.mydsl.tAB.OperationUnaireScript
   * @generated
   */
  EClass getOperationUnaireScript();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.tAB.OperationUnaireScript#getOperation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operation</em>'.
   * @see org.xtext.example.mydsl.tAB.OperationUnaireScript#getOperation()
   * @see #getOperationUnaireScript()
   * @generated
   */
  EAttribute getOperationUnaireScript_Operation();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.tAB.OperationUnaireScript#getOperands <em>Operands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Operands</em>'.
   * @see org.xtext.example.mydsl.tAB.OperationUnaireScript#getOperands()
   * @see #getOperationUnaireScript()
   * @generated
   */
  EReference getOperationUnaireScript_Operands();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.tAB.OperationBinaireScript <em>Operation Binaire Script</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operation Binaire Script</em>'.
   * @see org.xtext.example.mydsl.tAB.OperationBinaireScript
   * @generated
   */
  EClass getOperationBinaireScript();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.tAB.OperationBinaireScript#getOperation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operation</em>'.
   * @see org.xtext.example.mydsl.tAB.OperationBinaireScript#getOperation()
   * @see #getOperationBinaireScript()
   * @generated
   */
  EAttribute getOperationBinaireScript_Operation();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.tAB.OperationBinaireScript#getOperand <em>Operand</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Operand</em>'.
   * @see org.xtext.example.mydsl.tAB.OperationBinaireScript#getOperand()
   * @see #getOperationBinaireScript()
   * @generated
   */
  EReference getOperationBinaireScript_Operand();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.tAB.Operand <em>Operand</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operand</em>'.
   * @see org.xtext.example.mydsl.tAB.Operand
   * @generated
   */
  EClass getOperand();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.tAB.Calcul <em>Calcul</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Calcul</em>'.
   * @see org.xtext.example.mydsl.tAB.Calcul
   * @generated
   */
  EClass getCalcul();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.tAB.Calcul#getOperation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Operation</em>'.
   * @see org.xtext.example.mydsl.tAB.Calcul#getOperation()
   * @see #getCalcul()
   * @generated
   */
  EReference getCalcul_Operation();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl.tAB.OperationUnaireType <em>Operation Unaire Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Operation Unaire Type</em>'.
   * @see org.xtext.example.mydsl.tAB.OperationUnaireType
   * @generated
   */
  EEnum getOperationUnaireType();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl.tAB.OperationBinaireType <em>Operation Binaire Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Operation Binaire Type</em>'.
   * @see org.xtext.example.mydsl.tAB.OperationBinaireType
   * @generated
   */
  EEnum getOperationBinaireType();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl.tAB.TypePrimitifPython <em>Type Primitif Python</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Type Primitif Python</em>'.
   * @see org.xtext.example.mydsl.tAB.TypePrimitifPython
   * @generated
   */
  EEnum getTypePrimitifPython();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl.tAB.OperateurBinaireType <em>Operateur Binaire Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Operateur Binaire Type</em>'.
   * @see org.xtext.example.mydsl.tAB.OperateurBinaireType
   * @generated
   */
  EEnum getOperateurBinaireType();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl.tAB.OperateurUnaireType <em>Operateur Unaire Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Operateur Unaire Type</em>'.
   * @see org.xtext.example.mydsl.tAB.OperateurUnaireType
   * @generated
   */
  EEnum getOperateurUnaireType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TABFactory getTABFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.tAB.impl.TableurImpl <em>Tableur</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.tAB.impl.TableurImpl
     * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getTableur()
     * @generated
     */
    EClass TABLEUR = eINSTANCE.getTableur();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TABLEUR__NAME = eINSTANCE.getTableur_Name();

    /**
     * The meta object literal for the '<em><b>Tables</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TABLEUR__TABLES = eINSTANCE.getTableur_Tables();

    /**
     * The meta object literal for the '<em><b>Catalogue</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TABLEUR__CATALOGUE = eINSTANCE.getTableur_Catalogue();

    /**
     * The meta object literal for the '<em><b>Script</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TABLEUR__SCRIPT = eINSTANCE.getTableur_Script();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.tAB.impl.ColonneImpl <em>Colonne</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.tAB.impl.ColonneImpl
     * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getColonne()
     * @generated
     */
    EClass COLONNE = eINSTANCE.getColonne();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLONNE__NAME = eINSTANCE.getColonne_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.tAB.impl.OperationImpl <em>Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.tAB.impl.OperationImpl
     * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getOperation()
     * @generated
     */
    EClass OPERATION = eINSTANCE.getOperation();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.tAB.impl.OperateurUnaireImpl <em>Operateur Unaire</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.tAB.impl.OperateurUnaireImpl
     * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getOperateurUnaire()
     * @generated
     */
    EClass OPERATEUR_UNAIRE = eINSTANCE.getOperateurUnaire();

    /**
     * The meta object literal for the '<em><b>Kind</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATEUR_UNAIRE__KIND = eINSTANCE.getOperateurUnaire_Kind();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.tAB.impl.OperateurBinaireImpl <em>Operateur Binaire</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.tAB.impl.OperateurBinaireImpl
     * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getOperateurBinaire()
     * @generated
     */
    EClass OPERATEUR_BINAIRE = eINSTANCE.getOperateurBinaire();

    /**
     * The meta object literal for the '<em><b>Kind</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATEUR_BINAIRE__KIND = eINSTANCE.getOperateurBinaire_Kind();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.tAB.impl.TableImpl <em>Table</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.tAB.impl.TableImpl
     * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getTable()
     * @generated
     */
    EClass TABLE = eINSTANCE.getTable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TABLE__NAME = eINSTANCE.getTable_Name();

    /**
     * The meta object literal for the '<em><b>Colonnes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TABLE__COLONNES = eINSTANCE.getTable_Colonnes();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.tAB.impl.ColonneInputImpl <em>Colonne Input</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.tAB.impl.ColonneInputImpl
     * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getColonneInput()
     * @generated
     */
    EClass COLONNE_INPUT = eINSTANCE.getColonneInput();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.tAB.impl.ColonneOutputImpl <em>Colonne Output</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.tAB.impl.ColonneOutputImpl
     * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getColonneOutput()
     * @generated
     */
    EClass COLONNE_OUTPUT = eINSTANCE.getColonneOutput();

    /**
     * The meta object literal for the '<em><b>Operations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLONNE_OUTPUT__OPERATIONS = eINSTANCE.getColonneOutput_Operations();

    /**
     * The meta object literal for the '<em><b>Colonnes</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLONNE_OUTPUT__COLONNES = eINSTANCE.getColonneOutput_Colonnes();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.tAB.impl.CatalogueImpl <em>Catalogue</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.tAB.impl.CatalogueImpl
     * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getCatalogue()
     * @generated
     */
    EClass CATALOGUE = eINSTANCE.getCatalogue();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CATALOGUE__NAME = eINSTANCE.getCatalogue_Name();

    /**
     * The meta object literal for the '<em><b>Algorithmes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CATALOGUE__ALGORITHMES = eINSTANCE.getCatalogue_Algorithmes();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.tAB.impl.AlgorithmeImpl <em>Algorithme</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.tAB.impl.AlgorithmeImpl
     * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getAlgorithme()
     * @generated
     */
    EClass ALGORITHME = eINSTANCE.getAlgorithme();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALGORITHME__NAME = eINSTANCE.getAlgorithme_Name();

    /**
     * The meta object literal for the '<em><b>Entrees</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALGORITHME__ENTREES = eINSTANCE.getAlgorithme_Entrees();

    /**
     * The meta object literal for the '<em><b>Sorties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALGORITHME__SORTIES = eINSTANCE.getAlgorithme_Sorties();

    /**
     * The meta object literal for the '<em><b>Documentation</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALGORITHME__DOCUMENTATION = eINSTANCE.getAlgorithme_Documentation();

    /**
     * The meta object literal for the '<em><b>Ressource</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALGORITHME__RESSOURCE = eINSTANCE.getAlgorithme_Ressource();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.tAB.impl.EntreeImpl <em>Entree</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.tAB.impl.EntreeImpl
     * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getEntree()
     * @generated
     */
    EClass ENTREE = eINSTANCE.getEntree();

    /**
     * The meta object literal for the '<em><b>Parametres</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTREE__PARAMETRES = eINSTANCE.getEntree_Parametres();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.tAB.impl.SortieImpl <em>Sortie</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.tAB.impl.SortieImpl
     * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getSortie()
     * @generated
     */
    EClass SORTIE = eINSTANCE.getSortie();

    /**
     * The meta object literal for the '<em><b>Parametres</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SORTIE__PARAMETRES = eINSTANCE.getSortie_Parametres();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.tAB.impl.ParametreImpl <em>Parametre</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.tAB.impl.ParametreImpl
     * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getParametre()
     * @generated
     */
    EClass PARAMETRE = eINSTANCE.getParametre();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETRE__NAME = eINSTANCE.getParametre_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETRE__TYPE = eINSTANCE.getParametre_Type();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.tAB.impl.DocumentationImpl <em>Documentation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.tAB.impl.DocumentationImpl
     * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getDocumentation()
     * @generated
     */
    EClass DOCUMENTATION = eINSTANCE.getDocumentation();

    /**
     * The meta object literal for the '<em><b>Texte</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DOCUMENTATION__TEXTE = eINSTANCE.getDocumentation_Texte();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.tAB.impl.RessourceImpl <em>Ressource</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.tAB.impl.RessourceImpl
     * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getRessource()
     * @generated
     */
    EClass RESSOURCE = eINSTANCE.getRessource();

    /**
     * The meta object literal for the '<em><b>Chemin</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RESSOURCE__CHEMIN = eINSTANCE.getRessource_Chemin();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.tAB.impl.ScriptImpl <em>Script</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.tAB.impl.ScriptImpl
     * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getScript()
     * @generated
     */
    EClass SCRIPT = eINSTANCE.getScript();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCRIPT__NAME = eINSTANCE.getScript_Name();

    /**
     * The meta object literal for the '<em><b>Entrees</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCRIPT__ENTREES = eINSTANCE.getScript_Entrees();

    /**
     * The meta object literal for the '<em><b>Sorties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCRIPT__SORTIES = eINSTANCE.getScript_Sorties();

    /**
     * The meta object literal for the '<em><b>Calculs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCRIPT__CALCULS = eINSTANCE.getScript_Calculs();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.tAB.impl.EntreeScriptImpl <em>Entree Script</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.tAB.impl.EntreeScriptImpl
     * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getEntreeScript()
     * @generated
     */
    EClass ENTREE_SCRIPT = eINSTANCE.getEntreeScript();

    /**
     * The meta object literal for the '<em><b>Parametres</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTREE_SCRIPT__PARAMETRES = eINSTANCE.getEntreeScript_Parametres();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.tAB.impl.SortieScriptImpl <em>Sortie Script</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.tAB.impl.SortieScriptImpl
     * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getSortieScript()
     * @generated
     */
    EClass SORTIE_SCRIPT = eINSTANCE.getSortieScript();

    /**
     * The meta object literal for the '<em><b>Parametres</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SORTIE_SCRIPT__PARAMETRES = eINSTANCE.getSortieScript_Parametres();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.tAB.impl.OperationScriptImpl <em>Operation Script</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.tAB.impl.OperationScriptImpl
     * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getOperationScript()
     * @generated
     */
    EClass OPERATION_SCRIPT = eINSTANCE.getOperationScript();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.tAB.impl.OperationUnaireScriptImpl <em>Operation Unaire Script</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.tAB.impl.OperationUnaireScriptImpl
     * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getOperationUnaireScript()
     * @generated
     */
    EClass OPERATION_UNAIRE_SCRIPT = eINSTANCE.getOperationUnaireScript();

    /**
     * The meta object literal for the '<em><b>Operation</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATION_UNAIRE_SCRIPT__OPERATION = eINSTANCE.getOperationUnaireScript_Operation();

    /**
     * The meta object literal for the '<em><b>Operands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERATION_UNAIRE_SCRIPT__OPERANDS = eINSTANCE.getOperationUnaireScript_Operands();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.tAB.impl.OperationBinaireScriptImpl <em>Operation Binaire Script</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.tAB.impl.OperationBinaireScriptImpl
     * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getOperationBinaireScript()
     * @generated
     */
    EClass OPERATION_BINAIRE_SCRIPT = eINSTANCE.getOperationBinaireScript();

    /**
     * The meta object literal for the '<em><b>Operation</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATION_BINAIRE_SCRIPT__OPERATION = eINSTANCE.getOperationBinaireScript_Operation();

    /**
     * The meta object literal for the '<em><b>Operand</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERATION_BINAIRE_SCRIPT__OPERAND = eINSTANCE.getOperationBinaireScript_Operand();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.tAB.impl.OperandImpl <em>Operand</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.tAB.impl.OperandImpl
     * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getOperand()
     * @generated
     */
    EClass OPERAND = eINSTANCE.getOperand();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.tAB.impl.CalculImpl <em>Calcul</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.tAB.impl.CalculImpl
     * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getCalcul()
     * @generated
     */
    EClass CALCUL = eINSTANCE.getCalcul();

    /**
     * The meta object literal for the '<em><b>Operation</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CALCUL__OPERATION = eINSTANCE.getCalcul_Operation();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.tAB.OperationUnaireType <em>Operation Unaire Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.tAB.OperationUnaireType
     * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getOperationUnaireType()
     * @generated
     */
    EEnum OPERATION_UNAIRE_TYPE = eINSTANCE.getOperationUnaireType();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.tAB.OperationBinaireType <em>Operation Binaire Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.tAB.OperationBinaireType
     * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getOperationBinaireType()
     * @generated
     */
    EEnum OPERATION_BINAIRE_TYPE = eINSTANCE.getOperationBinaireType();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.tAB.TypePrimitifPython <em>Type Primitif Python</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.tAB.TypePrimitifPython
     * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getTypePrimitifPython()
     * @generated
     */
    EEnum TYPE_PRIMITIF_PYTHON = eINSTANCE.getTypePrimitifPython();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.tAB.OperateurBinaireType <em>Operateur Binaire Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.tAB.OperateurBinaireType
     * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getOperateurBinaireType()
     * @generated
     */
    EEnum OPERATEUR_BINAIRE_TYPE = eINSTANCE.getOperateurBinaireType();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.tAB.OperateurUnaireType <em>Operateur Unaire Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.tAB.OperateurUnaireType
     * @see org.xtext.example.mydsl.tAB.impl.TABPackageImpl#getOperateurUnaireType()
     * @generated
     */
    EEnum OPERATEUR_UNAIRE_TYPE = eINSTANCE.getOperateurUnaireType();

  }

} //TABPackage
