/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.tAB.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.tAB.ColonneInput;
import org.xtext.example.mydsl.tAB.TABPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Colonne Input</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ColonneInputImpl extends ColonneImpl implements ColonneInput
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ColonneInputImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TABPackage.Literals.COLONNE_INPUT;
  }

} //ColonneInputImpl
