/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.tAB.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.tAB.Calcul;
import org.xtext.example.mydsl.tAB.EntreeScript;
import org.xtext.example.mydsl.tAB.Script;
import org.xtext.example.mydsl.tAB.SortieScript;
import org.xtext.example.mydsl.tAB.TABPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Script</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.tAB.impl.ScriptImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.tAB.impl.ScriptImpl#getEntrees <em>Entrees</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.tAB.impl.ScriptImpl#getSorties <em>Sorties</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.tAB.impl.ScriptImpl#getCalculs <em>Calculs</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ScriptImpl extends MinimalEObjectImpl.Container implements Script
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getEntrees() <em>Entrees</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntrees()
   * @generated
   * @ordered
   */
  protected EList<EntreeScript> entrees;

  /**
   * The cached value of the '{@link #getSorties() <em>Sorties</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSorties()
   * @generated
   * @ordered
   */
  protected EList<SortieScript> sorties;

  /**
   * The cached value of the '{@link #getCalculs() <em>Calculs</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCalculs()
   * @generated
   * @ordered
   */
  protected EList<Calcul> calculs;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ScriptImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TABPackage.Literals.SCRIPT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TABPackage.SCRIPT__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<EntreeScript> getEntrees()
  {
    if (entrees == null)
    {
      entrees = new EObjectContainmentEList<EntreeScript>(EntreeScript.class, this, TABPackage.SCRIPT__ENTREES);
    }
    return entrees;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<SortieScript> getSorties()
  {
    if (sorties == null)
    {
      sorties = new EObjectContainmentEList<SortieScript>(SortieScript.class, this, TABPackage.SCRIPT__SORTIES);
    }
    return sorties;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Calcul> getCalculs()
  {
    if (calculs == null)
    {
      calculs = new EObjectContainmentEList<Calcul>(Calcul.class, this, TABPackage.SCRIPT__CALCULS);
    }
    return calculs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case TABPackage.SCRIPT__ENTREES:
        return ((InternalEList<?>)getEntrees()).basicRemove(otherEnd, msgs);
      case TABPackage.SCRIPT__SORTIES:
        return ((InternalEList<?>)getSorties()).basicRemove(otherEnd, msgs);
      case TABPackage.SCRIPT__CALCULS:
        return ((InternalEList<?>)getCalculs()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TABPackage.SCRIPT__NAME:
        return getName();
      case TABPackage.SCRIPT__ENTREES:
        return getEntrees();
      case TABPackage.SCRIPT__SORTIES:
        return getSorties();
      case TABPackage.SCRIPT__CALCULS:
        return getCalculs();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TABPackage.SCRIPT__NAME:
        setName((String)newValue);
        return;
      case TABPackage.SCRIPT__ENTREES:
        getEntrees().clear();
        getEntrees().addAll((Collection<? extends EntreeScript>)newValue);
        return;
      case TABPackage.SCRIPT__SORTIES:
        getSorties().clear();
        getSorties().addAll((Collection<? extends SortieScript>)newValue);
        return;
      case TABPackage.SCRIPT__CALCULS:
        getCalculs().clear();
        getCalculs().addAll((Collection<? extends Calcul>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TABPackage.SCRIPT__NAME:
        setName(NAME_EDEFAULT);
        return;
      case TABPackage.SCRIPT__ENTREES:
        getEntrees().clear();
        return;
      case TABPackage.SCRIPT__SORTIES:
        getSorties().clear();
        return;
      case TABPackage.SCRIPT__CALCULS:
        getCalculs().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TABPackage.SCRIPT__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case TABPackage.SCRIPT__ENTREES:
        return entrees != null && !entrees.isEmpty();
      case TABPackage.SCRIPT__SORTIES:
        return sorties != null && !sorties.isEmpty();
      case TABPackage.SCRIPT__CALCULS:
        return calculs != null && !calculs.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //ScriptImpl
