/**
 * generated by Xtext 2.32.0
 */
package org.xtext.tAB.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.tAB.OperationScript;
import org.xtext.tAB.TABPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Operation Script</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class OperationScriptImpl extends OperandImpl implements OperationScript
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OperationScriptImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TABPackage.Literals.OPERATION_SCRIPT;
  }

} //OperationScriptImpl
