/**
 * generated by Xtext 2.32.0
 */
package org.xtext.tAB;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Algorithme</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.tAB.Algorithme#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.tAB.Algorithme#getEntrees <em>Entrees</em>}</li>
 *   <li>{@link org.xtext.tAB.Algorithme#getSorties <em>Sorties</em>}</li>
 *   <li>{@link org.xtext.tAB.Algorithme#getDocumentation <em>Documentation</em>}</li>
 *   <li>{@link org.xtext.tAB.Algorithme#getRessource <em>Ressource</em>}</li>
 * </ul>
 *
 * @see org.xtext.tAB.TABPackage#getAlgorithme()
 * @model
 * @generated
 */
public interface Algorithme extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.tAB.TABPackage#getAlgorithme_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.tAB.Algorithme#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Entrees</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.tAB.Entree}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entrees</em>' containment reference list.
   * @see org.xtext.tAB.TABPackage#getAlgorithme_Entrees()
   * @model containment="true"
   * @generated
   */
  EList<Entree> getEntrees();

  /**
   * Returns the value of the '<em><b>Sorties</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.tAB.Sortie}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sorties</em>' containment reference list.
   * @see org.xtext.tAB.TABPackage#getAlgorithme_Sorties()
   * @model containment="true"
   * @generated
   */
  EList<Sortie> getSorties();

  /**
   * Returns the value of the '<em><b>Documentation</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.tAB.Documentation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Documentation</em>' containment reference list.
   * @see org.xtext.tAB.TABPackage#getAlgorithme_Documentation()
   * @model containment="true"
   * @generated
   */
  EList<Documentation> getDocumentation();

  /**
   * Returns the value of the '<em><b>Ressource</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.tAB.Ressource}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ressource</em>' containment reference list.
   * @see org.xtext.tAB.TABPackage#getAlgorithme_Ressource()
   * @model containment="true"
   * @generated
   */
  EList<Ressource> getRessource();

} // Algorithme
