/**
 * generated by Xtext 2.32.0
 */
package org.xtext.tAB;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Catalogue</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.tAB.Catalogue#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.tAB.Catalogue#getAlgorithmes <em>Algorithmes</em>}</li>
 * </ul>
 *
 * @see org.xtext.tAB.TABPackage#getCatalogue()
 * @model
 * @generated
 */
public interface Catalogue extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.tAB.TABPackage#getCatalogue_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.tAB.Catalogue#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Algorithmes</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.tAB.Algorithme}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Algorithmes</em>' containment reference list.
   * @see org.xtext.tAB.TABPackage#getCatalogue_Algorithmes()
   * @model containment="true"
   * @generated
   */
  EList<Algorithme> getAlgorithmes();

} // Catalogue
