/**
 * generated by Xtext 2.32.0
 */
package org.xtext.tAB;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Colonne Output</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.tAB.TABPackage#getColonneOutput()
 * @model
 * @generated
 */
public interface ColonneOutput extends Colonne
{
} // ColonneOutput
