/**
 * generated by Xtext 2.32.0
 */
package org.xtext.tAB;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Documentation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.tAB.Documentation#getTexte <em>Texte</em>}</li>
 * </ul>
 *
 * @see org.xtext.tAB.TABPackage#getDocumentation()
 * @model
 * @generated
 */
public interface Documentation extends EObject
{
  /**
   * Returns the value of the '<em><b>Texte</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Texte</em>' attribute.
   * @see #setTexte(String)
   * @see org.xtext.tAB.TABPackage#getDocumentation_Texte()
   * @model
   * @generated
   */
  String getTexte();

  /**
   * Sets the value of the '{@link org.xtext.tAB.Documentation#getTexte <em>Texte</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Texte</em>' attribute.
   * @see #getTexte()
   * @generated
   */
  void setTexte(String value);

} // Documentation
