/**
 * generated by Xtext 2.32.0
 */
package org.xtext.tAB;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation Unaire</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.tAB.OperationUnaire#getKind <em>Kind</em>}</li>
 * </ul>
 *
 * @see org.xtext.tAB.TABPackage#getOperationUnaire()
 * @model
 * @generated
 */
public interface OperationUnaire extends Operation
{
  /**
   * Returns the value of the '<em><b>Kind</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.tAB.OperationUnaireType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Kind</em>' attribute.
   * @see org.xtext.tAB.OperationUnaireType
   * @see #setKind(OperationUnaireType)
   * @see org.xtext.tAB.TABPackage#getOperationUnaire_Kind()
   * @model
   * @generated
   */
  OperationUnaireType getKind();

  /**
   * Sets the value of the '{@link org.xtext.tAB.OperationUnaire#getKind <em>Kind</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Kind</em>' attribute.
   * @see org.xtext.tAB.OperationUnaireType
   * @see #getKind()
   * @generated
   */
  void setKind(OperationUnaireType value);

} // OperationUnaire
