/**
 * generated by Xtext 2.32.0
 */
package org.xtext.tAB;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation Script</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.tAB.TABPackage#getOperationScript()
 * @model
 * @generated
 */
public interface OperationScript extends Operand
{
} // OperationScript
