/**
 * generated by Xtext 2.32.0
 */
package org.xtext.tAB;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation Binaire</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.tAB.OperationBinaire#getKind <em>Kind</em>}</li>
 * </ul>
 *
 * @see org.xtext.tAB.TABPackage#getOperationBinaire()
 * @model
 * @generated
 */
public interface OperationBinaire extends Operation
{
  /**
   * Returns the value of the '<em><b>Kind</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.tAB.OperationBinaireType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Kind</em>' attribute.
   * @see org.xtext.tAB.OperationBinaireType
   * @see #setKind(OperationBinaireType)
   * @see org.xtext.tAB.TABPackage#getOperationBinaire_Kind()
   * @model
   * @generated
   */
  OperationBinaireType getKind();

  /**
   * Sets the value of the '{@link org.xtext.tAB.OperationBinaire#getKind <em>Kind</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Kind</em>' attribute.
   * @see org.xtext.tAB.OperationBinaireType
   * @see #getKind()
   * @generated
   */
  void setKind(OperationBinaireType value);

} // OperationBinaire
