/**
 * generated by Xtext 2.32.0
 */
package org.xtext.tAB;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.tAB.TABPackage
 * @generated
 */
public interface TABFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TABFactory eINSTANCE = org.xtext.tAB.impl.TABFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Tableur</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tableur</em>'.
   * @generated
   */
  Tableur createTableur();

  /**
   * Returns a new object of class '<em>Colonne</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Colonne</em>'.
   * @generated
   */
  Colonne createColonne();

  /**
   * Returns a new object of class '<em>Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Operation</em>'.
   * @generated
   */
  Operation createOperation();

  /**
   * Returns a new object of class '<em>Operation Unaire</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Operation Unaire</em>'.
   * @generated
   */
  OperationUnaire createOperationUnaire();

  /**
   * Returns a new object of class '<em>Operation Binaire</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Operation Binaire</em>'.
   * @generated
   */
  OperationBinaire createOperationBinaire();

  /**
   * Returns a new object of class '<em>Table</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Table</em>'.
   * @generated
   */
  Table createTable();

  /**
   * Returns a new object of class '<em>Colonne Input</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Colonne Input</em>'.
   * @generated
   */
  ColonneInput createColonneInput();

  /**
   * Returns a new object of class '<em>Colonne Output</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Colonne Output</em>'.
   * @generated
   */
  ColonneOutput createColonneOutput();

  /**
   * Returns a new object of class '<em>Catalogue</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Catalogue</em>'.
   * @generated
   */
  Catalogue createCatalogue();

  /**
   * Returns a new object of class '<em>Algorithme</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Algorithme</em>'.
   * @generated
   */
  Algorithme createAlgorithme();

  /**
   * Returns a new object of class '<em>Entree</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entree</em>'.
   * @generated
   */
  Entree createEntree();

  /**
   * Returns a new object of class '<em>Sortie</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sortie</em>'.
   * @generated
   */
  Sortie createSortie();

  /**
   * Returns a new object of class '<em>Parametre</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Parametre</em>'.
   * @generated
   */
  Parametre createParametre();

  /**
   * Returns a new object of class '<em>Documentation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Documentation</em>'.
   * @generated
   */
  Documentation createDocumentation();

  /**
   * Returns a new object of class '<em>Ressource</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ressource</em>'.
   * @generated
   */
  Ressource createRessource();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  TABPackage getTABPackage();

} //TABFactory
