/**
 * generated by Xtext 2.32.0
 */
package org.xtext.tAB;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.tAB.TABFactory
 * @model kind="package"
 * @generated
 */
public interface TABPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "tAB";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/TAB";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "tAB";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TABPackage eINSTANCE = org.xtext.tAB.impl.TABPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.tAB.impl.TableurImpl <em>Tableur</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.tAB.impl.TableurImpl
   * @see org.xtext.tAB.impl.TABPackageImpl#getTableur()
   * @generated
   */
  int TABLEUR = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLEUR__NAME = 0;

  /**
   * The feature id for the '<em><b>Tables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLEUR__TABLES = 1;

  /**
   * The number of structural features of the '<em>Tableur</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLEUR_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.tAB.impl.ColonneImpl <em>Colonne</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.tAB.impl.ColonneImpl
   * @see org.xtext.tAB.impl.TABPackageImpl#getColonne()
   * @generated
   */
  int COLONNE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE__NAME = 0;

  /**
   * The number of structural features of the '<em>Colonne</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.tAB.impl.TableImpl <em>Table</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.tAB.impl.TableImpl
   * @see org.xtext.tAB.impl.TABPackageImpl#getTable()
   * @generated
   */
  int TABLE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE__NAME = 0;

  /**
   * The feature id for the '<em><b>Colonnes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE__COLONNES = 1;

  /**
   * The number of structural features of the '<em>Table</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.tAB.impl.ColonneInputImpl <em>Colonne Input</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.tAB.impl.ColonneInputImpl
   * @see org.xtext.tAB.impl.TABPackageImpl#getColonneInput()
   * @generated
   */
  int COLONNE_INPUT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE_INPUT__NAME = COLONNE__NAME;

  /**
   * The number of structural features of the '<em>Colonne Input</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE_INPUT_FEATURE_COUNT = COLONNE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.tAB.impl.ColonneOutputImpl <em>Colonne Output</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.tAB.impl.ColonneOutputImpl
   * @see org.xtext.tAB.impl.TABPackageImpl#getColonneOutput()
   * @generated
   */
  int COLONNE_OUTPUT = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE_OUTPUT__NAME = COLONNE__NAME;

  /**
   * The number of structural features of the '<em>Colonne Output</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE_OUTPUT_FEATURE_COUNT = COLONNE_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link org.xtext.tAB.Tableur <em>Tableur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tableur</em>'.
   * @see org.xtext.tAB.Tableur
   * @generated
   */
  EClass getTableur();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.tAB.Tableur#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.tAB.Tableur#getName()
   * @see #getTableur()
   * @generated
   */
  EAttribute getTableur_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.tAB.Tableur#getTables <em>Tables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tables</em>'.
   * @see org.xtext.tAB.Tableur#getTables()
   * @see #getTableur()
   * @generated
   */
  EReference getTableur_Tables();

  /**
   * Returns the meta object for class '{@link org.xtext.tAB.Colonne <em>Colonne</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Colonne</em>'.
   * @see org.xtext.tAB.Colonne
   * @generated
   */
  EClass getColonne();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.tAB.Colonne#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.tAB.Colonne#getName()
   * @see #getColonne()
   * @generated
   */
  EAttribute getColonne_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.tAB.Table <em>Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Table</em>'.
   * @see org.xtext.tAB.Table
   * @generated
   */
  EClass getTable();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.tAB.Table#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.tAB.Table#getName()
   * @see #getTable()
   * @generated
   */
  EAttribute getTable_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.tAB.Table#getColonnes <em>Colonnes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Colonnes</em>'.
   * @see org.xtext.tAB.Table#getColonnes()
   * @see #getTable()
   * @generated
   */
  EReference getTable_Colonnes();

  /**
   * Returns the meta object for class '{@link org.xtext.tAB.ColonneInput <em>Colonne Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Colonne Input</em>'.
   * @see org.xtext.tAB.ColonneInput
   * @generated
   */
  EClass getColonneInput();

  /**
   * Returns the meta object for class '{@link org.xtext.tAB.ColonneOutput <em>Colonne Output</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Colonne Output</em>'.
   * @see org.xtext.tAB.ColonneOutput
   * @generated
   */
  EClass getColonneOutput();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TABFactory getTABFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.tAB.impl.TableurImpl <em>Tableur</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.tAB.impl.TableurImpl
     * @see org.xtext.tAB.impl.TABPackageImpl#getTableur()
     * @generated
     */
    EClass TABLEUR = eINSTANCE.getTableur();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TABLEUR__NAME = eINSTANCE.getTableur_Name();

    /**
     * The meta object literal for the '<em><b>Tables</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TABLEUR__TABLES = eINSTANCE.getTableur_Tables();

    /**
     * The meta object literal for the '{@link org.xtext.tAB.impl.ColonneImpl <em>Colonne</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.tAB.impl.ColonneImpl
     * @see org.xtext.tAB.impl.TABPackageImpl#getColonne()
     * @generated
     */
    EClass COLONNE = eINSTANCE.getColonne();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLONNE__NAME = eINSTANCE.getColonne_Name();

    /**
     * The meta object literal for the '{@link org.xtext.tAB.impl.TableImpl <em>Table</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.tAB.impl.TableImpl
     * @see org.xtext.tAB.impl.TABPackageImpl#getTable()
     * @generated
     */
    EClass TABLE = eINSTANCE.getTable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TABLE__NAME = eINSTANCE.getTable_Name();

    /**
     * The meta object literal for the '<em><b>Colonnes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TABLE__COLONNES = eINSTANCE.getTable_Colonnes();

    /**
     * The meta object literal for the '{@link org.xtext.tAB.impl.ColonneInputImpl <em>Colonne Input</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.tAB.impl.ColonneInputImpl
     * @see org.xtext.tAB.impl.TABPackageImpl#getColonneInput()
     * @generated
     */
    EClass COLONNE_INPUT = eINSTANCE.getColonneInput();

    /**
     * The meta object literal for the '{@link org.xtext.tAB.impl.ColonneOutputImpl <em>Colonne Output</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.tAB.impl.ColonneOutputImpl
     * @see org.xtext.tAB.impl.TABPackageImpl#getColonneOutput()
     * @generated
     */
    EClass COLONNE_OUTPUT = eINSTANCE.getColonneOutput();

  }

} //TABPackage
