(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.
Require int.Int.
Require int.Power.

(* Why3 assumption *)
Inductive ref (a:Type) :=
  | mk_ref : a -> ref a.
Axiom ref_WhyType : forall (a:Type) {a_WT:WhyType a}, WhyType (ref a).
Existing Instance ref_WhyType.
Arguments mk_ref {a}.

(* Why3 assumption *)
Definition contents {a:Type} {a_WT:WhyType a} (v:ref a) : a :=
  match v with
  | mk_ref x => x
  end.

Parameter n: Z.

Axiom H : (0%Z < n)%Z.

Parameter v: Z.

Parameter r: Z.

Axiom H1 : (v <= n)%Z.

Parameter v1: Z.

Axiom H2 : (v1 = (2%Z * v)%Z).

Parameter r1: Z.

Axiom H3 : (r1 = (r + 1%Z)%Z).

(* Why3 goal *)
Theorem VC_logarithme : False.
Proof.


Qed.

