clear;
close all;
clc;

[J,I] = meshgrid(1:5,1:5);
G_norme = I+J;
E = [ 1 2 ; ...
      2 2 ; ...
      2 3 ; ...
      3 3 ; ...
      3 4 ; ...
      3 5 ];
indices_E = sub2ind(size(G_norme),E(:,1),E(:,2));

[M_inertie,C] = fonctions_TP3_proba('matrice_inertie',E,G_norme(indices_E));

C_th = [3.4848 2.5455];
    
M_th = [1.1589  0.5234; ...
        0.5234  0.4298];

erreur_approximation = 0.0001;
if ((       abs(C(1)-C_th(1))       < erreur_approximation) &&    ...
    (       abs(C(2)-C_th(2))       < erreur_approximation) &&    ...
    (abs(M_inertie(1,1)-M_th(1,1)) < erreur_approximation) && ...
    (abs(M_inertie(1,2)-M_th(1,2)) < erreur_approximation) && ...
    (abs(M_inertie(2,2)-M_th(2,2)) < erreur_approximation))
	fprintf('La fonction matrice_inertie semble correcte !\n');
else
	fprintf('Attention : probleme !!!\n');
end
