/**
 * generated by Xtext 2.32.0
 */
package fr.n7.pDL1;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Needed Ressource</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.pDL1.NeededRessource#getQuantity <em>Quantity</em>}</li>
 *   <li>{@link fr.n7.pDL1.NeededRessource#getRessource <em>Ressource</em>}</li>
 * </ul>
 *
 * @see fr.n7.pDL1.PDL1Package#getNeededRessource()
 * @model
 * @generated
 */
public interface NeededRessource extends EObject
{
  /**
   * Returns the value of the '<em><b>Quantity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Quantity</em>' attribute.
   * @see #setQuantity(int)
   * @see fr.n7.pDL1.PDL1Package#getNeededRessource_Quantity()
   * @model
   * @generated
   */
  int getQuantity();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.NeededRessource#getQuantity <em>Quantity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Quantity</em>' attribute.
   * @see #getQuantity()
   * @generated
   */
  void setQuantity(int value);

  /**
   * Returns the value of the '<em><b>Ressource</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ressource</em>' reference.
   * @see #setRessource(Ressource)
   * @see fr.n7.pDL1.PDL1Package#getNeededRessource_Ressource()
   * @model
   * @generated
   */
  Ressource getRessource();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.NeededRessource#getRessource <em>Ressource</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ressource</em>' reference.
   * @see #getRessource()
   * @generated
   */
  void setRessource(Ressource value);

} // NeededRessource
