/*
 * generated by Xtext 2.32.0
 */
package fr.n7.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPDL1ScopeProvider extends DelegatingScopeProvider {
}
