/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.tableur.ui.internal.TableurActivator;

public class TABUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TableurActivator.getInstance().getInjector("org.xtext.example.mydsl.TAB");
	}

}
