(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.
Require int.Int.

(* Why3 assumption *)
Inductive ref (a:Type) :=
  | mk_ref : a -> ref a.
Axiom ref_WhyType : forall (a:Type) {a_WT:WhyType a}, WhyType (ref a).
Existing Instance ref_WhyType.
Arguments mk_ref {a}.

(* Why3 assumption *)
Definition contents {a:Type} {a_WT:WhyType a} (v:ref a) : a :=
  match v with
  | mk_ref x => x
  end.

Parameter a: Z.

Parameter b: Z.

Axiom H : (0%Z <= a)%Z.

Axiom H1 : (0%Z < b)%Z.

Parameter r: Z.

Parameter q: Z.

Axiom H2 : (a = ((q * b)%Z + r)%Z).

Axiom H3 : (0%Z <= q)%Z.

Axiom H4 : (0%Z < b)%Z.

Axiom H5 : ~ (b <= r)%Z.

(* Why3 goal *)
Theorem VC_division : (((q * b)%Z + r)%Z = a) /\ ((0%Z <= r)%Z /\ (r < b)%Z).
Proof.
split.
rewrite <- H2.
reflexivity.
split.

Qed.

